FROM node:16-alpine

EXPOSE 5000

COPY package* ./

RUN npm install

COPY . .

RUN npm run build && npm install -g serve && \
  rm -rf /var/lib/apt/lists/* && \
  adduser -D appuser

USER appuser

CMD serve -s -l 5000 build