FROM node:16-alpine as build-stage

WORKDIR /usr/src/app

COPY package* ./

RUN npm install

COPY . .

RUN npm run build

FROM node:16-alpine

EXPOSE 5000

COPY --from=build-stage /usr/src/app/build ./build

RUN npm install -g serve && \
  adduser -D appuser

USER appuser

CMD serve -s -l 5000 build