FROM golang:1.16.15-alpine3.15 as build-stage

WORKDIR /usr/src/app

COPY . .

RUN CGO_ENABLED=0 go build -o /go/bin/server -a -ldflags '-extldflags "-static"' . 

FROM scratch

EXPOSE 8080

COPY --from=build-stage /go/bin/server /go/bin/server

ENTRYPOINT ["/go/bin/server"]